version: '3.7'
services:
  minio:
    build:
      context: ${SERVICE_2_SRC_DIR}
    env_file:
      - .env
    container_name: minio
    image: quay.io/minio/minio:RELEASE.2022-02-18T01-50-10Z
    volumes:
      - ./data:/data
    networks:
      - backend
      - reverse-proxy
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_ADDRESS: ':9000'
      MINIO_CONSOLE_ADDRESS: ':9001'
    command: minio server /data
  postgres:
    env_file:
      - .env
    restart: always
    image: postgres:13
    container_name: postgres_db
    networks:
      backend:
    ports:
      - 5432
    environment:
      POSTGRES_DB: nestserver
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
  app:
    container_name: app
    build:
      context: ${SERVICE_1_SRC_DIR}
#      target: development
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    networks:
      backend:
      reverse-proxy:
    command: npm run start
    env_file:
      - .env
    depends_on:
      - minio
      - postgres
    environment:
      - VIRTUAL_HOST=${SERVICE_DOMAIN}
      - LETSENCRYPT_HOST=${SERVICE_DOMAIN}
#      - NODE_ENV=production
      - PORT=3001
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
#    user: "node"
  frontend:
    build:
      context: ${INTERFACE_SRC_DIR}
      target: front
      dockerfile: Dockerfile
      args:
        - SERVICE_URL=${PROTOCOL}://${SERVICE_DOMAIN}
    expose:
      - 3000
    environment:
      - VIRTUAL_HOST=${INTERFACE_DOMAIN}
      - VIRTUAL_PORT=3000
      - PORT=3000
      - SERVICE_URL=${PROTOCOL}://${SERVICE_DOMAIN}
      - LETSENCRYPT_HOST=${INTERFACE_DOMAIN}
      - NODE_ENV=production
      - HOST=0.0.0.0
    networks:
      reverse-proxy:


networks:
  backend:
    driver: bridge
  reverse-proxy:
    external:
      name: reverse-proxy
volumes:
  postgres_data:
  minio_data:
    driver: local
